### ISSUE TITLE
DI/IoC Containers

### ISSUE THREAD

**Issue by jdscolam** [jpsingleton/ANCLAFS#1]
@jpsingleton this is an AWESOME idea!  Thank you for doing this.

Would you please add a section on DI/IoC containers?

**Comment by jpsingleton** [comment]
@jdscolam thanks! I'll add ninject, autofac, windsor etc. when I find some more time.
The built in DI is working pretty well for me so I haven't looked into this area too much.

Feel free to send a PR if you have some spare time soon. For example, this looks like the relevant issue for windsor https://github.com/castleproject/Windsor/issues/120 but I haven't tested any packages for it.

**Comment by jpsingleton** [comment]
I've added a bunch more stuff including DI, and published to https://anclafs.com.
