### ISSUE TITLE
Add schedulers

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/ANCLAFS#11]
https://github.com/quartznet/quartznet/issues/355

https://github.com/fluentscheduler/FluentScheduler
(can't find any mention of Core yet)

@GeorgeHahn

**Comment by GeorgeHahn** [comment]
See https://github.com/fluentscheduler/FluentScheduler/issues/67 → https://github.com/fluentscheduler/FluentScheduler/pull/69 → https://github.com/fluentscheduler/FluentScheduler/issues/83

**Comment by jpsingleton** [comment]
Done, thanks!

**Comment by tallesl** [comment]
Hi there. [FluentScheduler](https://github.com/fluentscheduler/FluentScheduler) maintainer here.

We do support .NET Core but ASP.NET Core support still in progress. [I added a note on our README stating it that](https://github.com/fluentscheduler/FluentScheduler#using-it-with-net-core).

**Comment by jpsingleton** [comment]
Thanks @tallesl. I'll tweak the ANCLAFS README.

**Comment by jpsingleton** [comment]
OK done, BTW you can do a blocking shutdown in ASP.NET Core. I'll add details to https://github.com/fluentscheduler/FluentScheduler/issues/94.
