### ISSUE TITLE
Adding NBitcoin to the List

### ISSUE THREAD

**Issue by simplexidev** [jpsingleton/ANCLAFS#16]
Hello!

I'm currently working with the developers of [NBitcoin](http://github.com/MetacoSA/NBitcoin) to add .NET Core compatibility. I figured since I've seen your repository, I would let you know about it. You can find the open issue [here](http://github.com/MetacoSA/NBitcoin/issues/176).
# **Information:**

**Project:** NBitcoin
**NuGet Install Command:** ---
**.NET Core Support:** [WIP](http://github.com/MetacoSA/NBitcoin/issues/176)
**ASP.NET Support:** No
**Website:**[GitHub](https://github.com/MetacoSA/NBitcoin)

**Comment by jpsingleton** [comment]
Looks very interesting. Thanks!

I'll take a closer look when I have time, but you could speed the process up by creating a pull request once you're happy with the WIP.

**Comment by jpsingleton** [comment]
Looks like this is supported on master now so I'll add it to the list.
