### ISSUE TITLE
FeatureSwitcher

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/ANCLAFS#30]
Update FeatureSwitcher if ported version gets released.

https://github.com/mexx/FeatureSwitcher/issues/10
https://github.com/mexx/FeatureSwitcher/pull/11

**Comment by mexx** [comment]
FYI: FeatureSwitcher now targets netstandard1.0. Please use 2.0.0 version.

**Comment by jpsingleton** [comment]
Great stuff, thanks.
