### ISSUE TITLE
Reconcile MS list

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/ANCLAFS#5]
Reconcile list of 106 projects from MS and merge in.

**Comment by martinwoodward** [comment]
Let me know if I can help with this once you have figured out how you want to structure the data.

**Comment by jpsingleton** [comment]
Will do. Thanks!

**Comment by jpsingleton** [comment]
I'll probably keep it simple for now, but if people find it useful then a more structured approach would be useful. Any ideas welcome.

**Comment by jpsingleton** [comment]
Done importing.
