### ISSUE TITLE
Add C# BitTorrent library if Core support added

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/ANCLAFS#6]
https://cheatdeath.github.io/research-bittorrent-doc
https://github.com/cheatdeath/research-bittorrent

Package [`JonSkeet.MiscUtil`](https://www.nuget.org/packages/JonSkeet.MiscUtil) for Core? Code not on GitHub, http://jonskeet.uk/csharp/miscutil. 
@jskeet

> JonSkeet.MiscUtil source code is fine for Core[...](https://news.ycombinator.com/item?id=12040309)

@cheatdeath

**Comment by jskeet** [comment]
I'd personally avoid using `JonSkeet.MiscUtil` if you can - the code in there is _really_ old, and I haven't been actively maintaining it. Of course, you're welcome to use it should you wish, but you may well want to just rewrite (or copy the code and check it carefully!) for the bits you're using.

**Comment by jpsingleton** [comment]
OK, thanks @jskeet. I'm not personally using it, but @cheatdeath is. As you say, probably best to use the code, not the package.
