### ISSUE TITLE
Add UI cross-platform frameworks

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/ANCLAFS#9]
Add these (and others?) to https://anclafs.com if work to support Core starts.

https://github.com/AvaloniaUI/Avalonia/issues/314 (maintainer @grokys?)

https://github.com/picoe/Eto/issues/457 (maintainer @cwensley?)

**Comment by kekekeks** [comment]
Regarding Avalonia: We could probably start porting to .NET Core right away, but that would only work for our Win32 and Direct2D backends. GTK# bindings don't support .NET Core yet and Skia# needs to be forked and recompiled.

For now almost entire Avalonia framework is built against PCL Profile7, so once these dependency issues are solved we'll add .NET Core build.

**Comment by jpsingleton** [comment]
Thanks for letting me know @kekekeks. I won't add these yet as there's currently no good UI story for .NET Core. I'll focus on web / console for now but hopefully there'll be some native GUIs in the future.

**Comment by jpsingleton** [comment]
Looks like [0.4.0](https://www.nuget.org/packages/Avalonia/) (alpha 4) is out. Can't see it in GitHub releases though.

**Comment by grokys** [comment]
@jpsingleton yeah I haven't been bothering with GirHub releases as they're kinda irrelevant to us as we use NuGet to ship releases. Would it help you if I also did a GitHub release?

**Comment by jpsingleton** [comment]
@grokys

I think the best place for release information would be near the top of the README. You can link to the [release notes on your blog](https://grokys.github.io/avalonia/avalonia-alpha4/) (the styles don't load over HTTPS BTW). You could copy/paste that post into a GitHub release if you like (or just link to it), but as long as it's somewhere in the repository it's probably fine.

The blog post isn't trivial to find and it's hard to see what state the release is in from NuGet. The package should probably be tagged as alpha too. For example, `0.4.0-alpha` or `0.4.0-alpha4`.

Anyway, it looks like .NET Core support is still a way off, but let me know if that changes.
